add jhook_copy_directory function

diff --git a/jepo b/jepo
--- a/jepo
+++ b/jepo
@@ -26,7 +26,7 @@ jepo_dir=".jepo"
 if [[ "$1" == "--hook-defs" ]]; then
 
   # delete and insert a PRODUCT_PACKAGES package in an mk file
-  _delete_insert_package () {
+  _jhookpriv_delete_insert_package () {
     del_package="$1"
     ins_package="$2"
     insert="$3" # 0 for (delete and) insert, otherwise delete only
@@ -78,17 +78,58 @@ if [[ "$1" == "--hook-defs" ]]; then
       echo "$line"
     done > "$out_file"
   }
+
+  # copy from to, relative to the working directory
+  _jhookpriv_cp_directory () {
+    from="$1"
+    to="$2"
+    echo "Copying (overwriting) \"$from\" to \"$to\"..."
+    if [[ ! -d "$from" ]]; then
+      echo "  Error: Source directory does not exist."
+      return 1
+    fi
   
-  delete_package () {
+    rm -r "$to"
+    error="$?"
+    if [[ "$error" == 0 ]]; then
+      echo "  rm -r terminates successfully."
+    else
+      echo "  rm -r terminates with error code $error"
+    fi
+  
+    mkdir -p "$to"
+    error="$?"
+    if [[ "$error" == 0 ]]; then
+      echo "  mkdir -p terminates successfully."
+    else
+      echo "  mkdir -p terminates with error code $error"
+    fi
+
+    cp -rTH "$from" "$to"
+    error="$?"
+    if [[ "$error" == 0 ]]; then
+      echo "  cp -rTH terminates successfully."
+    else
+      echo "  cp -rTH terminates with error code $error"
+    fi
+    return "$error"
+  }
+
+  jhook_delete_package () {
     package="$1"
     file="$2"
-    _delete_insert_package "$package" "$package" 1 "$file" "$file"
+    _jhookpriv_delete_insert_package "$package" "$package" 1 "$file" "$file"
   }
   
-  insert_package () {
+  jhook_insert_package () {
     package="$1"
     file="$2"
-    _delete_insert_package "$package" "$package" 0 "$file" "$file"
+    _jhookpriv_delete_insert_package "$package" "$package" 0 "$file" "$file"
+  }
+
+  jhook_copy_directory () {
+    dir="$1"
+    _jhookpriv_cp_directory "$jepo_dir/hook-src/$dir" "$dir"
   }
 
   return 0
